#index:
#    path: /
#    controller: BSApp\Controller\DefaultController::index



welcome:
  path: /
  controller: BSApp\Controller\WelcomeController::indexAction

bs_app_checkout:
  resource: 'routes/routing_checkout.yml'
  prefix: /cashbox


bs_app_checkout_quickbox:
 resource: 'routes/routing_checkout_quickbottom.yml'
 prefix: /cashbox/quickbutton

bs_app_data:
  resource: 'routes/routing_data.yml'
  prefix: /data

bs_app_data_plang:
  resource: 'routes/routing_data_plant.yml'
  prefix: /data/plant


bs_app_lable:
  resource: 'routes/routing_label.yml'
  prefix: /lable

bs_app_orders:
  resource: 'routes/routing_orders.yml'
  prefix: /orders

bs_app_product:
  resource: 'routes/routing_product.yml'
  prefix: /product

bs_app_stockkeeping:
  resource: 'routes/routing_stockkeeping.yml'
  prefix: "/data/stockkeeping"